name: Merge master to develop

on:
  push:
    branches:
      - master

jobs:
  merge_master_to_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Merge master -> development
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: development
          github_token: ${{ github.token }}
